CREATE TABLE musica(
    id  INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(50) NOT NULL,
    url VARCHAR(255) NOT NULL,
    CONSTRAINT pk_id_musica PRIMARY KEY (id)
)engine=InnoDB DEFAULT CHARSET=utf8;